Style/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Enabled: false  

Style/FrozenStringLiteralComment:
  Enabled: false  

Style/Documentation:
  Enabled: false  

Style/MixinUsage:
  Enabled: false 
   
Layout/EndOfLine:
  EnforcedStyle: lf

AllCops:
  Exclude:
    - 'db/schema.rb'
